[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "chmod +x start.sh"
]

[phases.build]
cmds = []

[start]
cmd = "/bin/bash /app/start.sh"

[variables]
PYTHONUNBUFFERED = "1"
